apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: docling
spec:
  params:
    - name: S3_BUCKET_PATH
      type: string
    - name: DOCLING_INPUT
      type: string
    - name: DOCLING_OUTPUT
      type: string
  workspaces:
    - name: jobs
      description: A workspace to mount the job YAML.
  steps:
    - name: run-docling-job
      image: quay.io/dataprep1/data-prep-kit/kubectl:latest
      env:
        - name: S3_BUCKET_PATH
          value: $(params.S3_BUCKET_PATH)
        - name: DOCLING_INPUT
          value: $(params.DOCLING_INPUT)
        - name: DOCLING_OUTPUT
          value: $(params.DOCLING_OUTPUT)

      script: |
        #!/bin/sh
        JOBFILE=/workspace/jobs/data-prep-kit/transforms/language/docling2parquet/docling2parquet-rayjob.yaml
        ##############################################################################
        ## Most jobs follow the same pattern, so we can templatize this in the future
        JOBNAME=`yq '.metadata.name' $JOBFILE`
        TMPFILE=$(mktemp)
        envsubst < "$JOBFILE" > "$TMPFILE"
        cat "$TMPFILE" && kubectl apply -f "$TMPFILE"
        echo "Watiing for Kubernetes rayjob/$JOBNAME to finish or timeout after 24h..."
        kubectl wait --for=jsonpath='{.status.jobDeploymentStatus}'=Complete rayjob/$JOBNAME --timeout=24h
        echo "Kubernetes rayjob/$JOBNAME completed. Check log for completion status..."
        ##############################################################################

