ARG BASE_IMAGE=docker.io/rayproject/ray:2.24.0-py310

FROM ${BASE_IMAGE}

# see https://docs.openshift.com/container-platform/4.17/openshift_images/create-images.html#use-uid_create-images
USER root
RUN chown ray:root /home/ray && chmod g=u /home/ray
USER ray

RUN pip install --upgrade --no-cache-dir pip

# install pytest
RUN pip install --no-cache-dir pytest

ARG PIP_INSTALL_EXTRA_ARGS
ARG DPK_WHEEL_FILE_NAME

RUN \
    sudo apt-get update \
    # for opencv, towhee
    && sudo apt-get install -y libgl1 libglib2.0-0 curl wget \
    && sudo apt-get clean

# Copy and install data processing libraries
# These are expected to be placed in the docker context before this is run (see the make image).
COPY --chmod=775 --chown=ray:root data-processing-dist data-processing-dist
RUN  pip install data-processing-dist/${DPK_WHEEL_FILE_NAME}[ray]


## Copy the python version of the tansform
COPY --chmod=775 --chown=ray:root dpk_docling2parquet/ dpk_docling2parquet/
COPY --chmod=775 --chown=ray:root requirements.txt requirements.txt
RUN pip install ${PIP_INSTALL_EXTRA_ARGS} -r requirements.txt

# Set environment
ENV PYTHONPATH /home/ray
ENV PATH="/home/ray/.local/bin:${PATH}"

# Download models
RUN docling-tools models download layout tableformer picture_classifier easyocr
#Models downloaded into: /home/ray/.cache/docling/models.
#Docling can now be configured for running offline using the local artifacts.
#Using the CLI: `docling --artifacts-path=/home/ray/.cache/docling/models FILE`


##2025-09-28 05:15:02,587 - WARNING - Ignored error while writing commit hash to /home/ray/.cache/huggingface/hub/models--ds4sd--docling-layout-heron/refs/main: [Errno 13] Permission denied: '/home/ray/.cache/huggingface/hub/models--ds4sd--docling-layout-heron/refs/main'.
##PermissionError: [Errno 13] Permission denied: '/home/ray/.cache/huggingface/hub/models--ds4sd--docling-layout-heron/blobs'
# Fix permissions on huggingface cache for docling models
# This is needed since the model download above seems to create files with wrong permission acceass on OCP.
USER root
RUN mkdir -p /home/ray/.cache/huggingface/hub/models--ds4sd--docling-layout-heron/blobs && \
   mkdir -p /home/ray/.cache/huggingface/hub/models--ds4sd--docling-layout-heron/refs && \
   chown -R ray:root /home/ray/.cache && \
   chmod -R g=u /home/ray/.cache
USER ray

# Parallelism
ENV OMP_NUM_THREADS=2

# Put these at the end since they seem to upset the docker cache.
ARG BUILD_DATE
ARG GIT_COMMIT
ARG TRANSFORM_PATH
ARG GIT_URL
ENV GIT_URL $GIT_URL
ENV TRANSFORM_PATH $TRANSFORM_PATH
ENV BUILD_DATE $BUILD_DATE
ENV GIT_COMMIT $GIT_COMMIT
LABEL build-date=$BUILD_DATE
LABEL git-commit=$GIT_COMMIT