FROM docker.io/python:3.12-slim

RUN pip install --upgrade --no-cache-dir pip

# install pytest
RUN pip install --no-cache-dir pytest


RUN \
    apt-get update \
    # for opencv, towhee
    && apt-get install -y libgl1 libglib2.0-0 curl wget \
    && apt-get clean

# Create a user and use it to run the transform
RUN useradd -d /home/dpk -ms /bin/bash -g root dpk
WORKDIR /home/dpk
USER dpk

ARG PIP_INSTALL_EXTRA_ARGS
ARG DPK_WHEEL_FILE_NAME

# Copy and install data processing libraries
# These are expected to be placed in the docker context before this is run (see the make image).
COPY --chown=dpk:root data-processing-dist/ data-processing-dist/
RUN  pip install data-processing-dist/${DPK_WHEEL_FILE_NAME}

# END OF STEPS destined for a data-prep-kit base image

COPY --chown=dpk:root dpk_docling2parquet/ dpk_docling2parquet/
COPY --chown=dpk:root requirements.txt requirements.txt
RUN pip install ${PIP_INSTALL_EXTRA_ARGS} -r requirements.txt

# Set environment
ENV PYTHONPATH=/home/dpk
ENV PATH="/home/dpk/.local/bin:${PATH}"
ENV HOME=/home/dpk

# Download models
RUN docling-tools models download layout tableformer picture_classifier easyocr

USER root
RUN mkdir -p /home/dpk/.cache/huggingface/hub/models--ds4sd--docling-layout-heron/blobs && \
   mkdir -p /home/dpk/.cache/huggingface/hub/models--ds4sd--docling-layout-heron/refs && \
   chown -R dpk:root /home/dpk/.cache && \
   chmod -R g=u /home/dpk
USER dpk


# Parallelism
ENV OMP_NUM_THREADS=2

# Put these at the end since they seem to upset the docker cache.
ARG BUILD_DATE
ARG GIT_COMMIT
ARG TRANSFORM_PATH
ARG GIT_URL
ENV GIT_URL $GIT_URL
ENV TRANSFORM_PATH=$TRANSFORM_PATH
ENV BUILD_DATE=$BUILD_DATE
ENV GIT_COMMIT=$GIT_COMMIT
LABEL build-date=$BUILD_DATE
LABEL git-commit=$GIT_COMMIT