apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: gwclassification
spec:
  workspaces:
    - name: dpk-pipeline-ws
  params:
    - name: S3_BUCKET_PATH
      description: Bucket name or bucket name and path for the root S3 folder (e.g.. bucket-wikimedia-1 or bucket-wikimedia-1/run1, etc) 
      type: string
    - name: DOCLING_INPUT
      type: string
      description: The input folder for the docling transform
    - name: DOCLING_OUTPUT
      type: string
      description: The output folder for the docling transform
    - name: EDEDUP_INPUT
      type: string
      description: The input folder for the EDedup transform
    - name: EDEDUP_OUTPUT
      type: string
      description: The output folder for the EDedup transform
    - name: GW_MATH_INPUT
      type: string
      description: The input folder for the GW Math Classifier
    - name: GW_MATH_OUTPUT
      type: string
      description: The output folder for the GW Math Classifier
  tasks:
    - name: execute-repo-task
      taskRef:
        name: repo
      workspaces:
        - name: jobs
          workspace: dpk-pipeline-ws
    - name: execute-docling-task
      taskRef:
        name: docling
      runAfter:
        - execute-repo-task
      workspaces:
        - name: jobs
          workspace: dpk-pipeline-ws
      params:
        - name: S3_BUCKET_PATH
          value: "$(params.S3_BUCKET_PATH)"
        - name: DOCLING_INPUT
          value: "$(params.DOCLING_INPUT)"
        - name: DOCLING_OUTPUT
          value: "$(params.DOCLING_OUTPUT)"
    - name: execute-ededup-task
      taskRef:
        name: ededup
      runAfter:
        - execute-docling-task
      workspaces:
        - name: jobs
          workspace: dpk-pipeline-ws
      params:
        - name: S3_BUCKET_PATH
          value: "$(params.S3_BUCKET_PATH)"
        - name: EDEDUP_INPUT
          value: "$(params.EDEDUP_INPUT)"
        - name: EDEDUP_OUTPUT
          value: "$(params.EDEDUP_OUTPUT)"
    - name: execute-gw-classification-task
      taskRef:
        name: gwclassification
      runAfter:
        - execute-ededup-task
      workspaces:
        - name: jobs
          workspace: dpk-pipeline-ws
      params:
        - name: S3_BUCKET_PATH
          value: "$(params.S3_BUCKET_PATH)" 
        - name: GW_MATH_OUTPUT
          value: "$(params.GW_MATH_OUTPUT)"  
        - name: GW_MATH_INPUT
          value: "$(params.GW_MATH_INPUT)"