FROM docker.io/python:3.12-slim

RUN pip install --upgrade --no-cache-dir pip
RUN pip install uv

# install pytest
RUN uv pip install --no-cache-dir  --system pytest

RUN \
    apt-get update \
    # for opencv, towhee
    && apt-get install -y libgl1 libglib2.0-0 curl vim wget \
    && apt-get clean

# Create a user and use it to run the transform
RUN useradd -d /home/dpk -ms /bin/bash -g root dpk
WORKDIR /home/dpk
USER dpk
RUN uv venv /home/dpk/venv
ENV PATH="/home/dpk/venv/bin:$PATH"

RUN uv pip install setuptools requests

ARG PIP_INSTALL_EXTRA_ARGS
ARG DPK_WHEEL_FILE_NAME

# Copy and install data processing libraries 
# These are expected to be placed in the docker context before this is run (see the make image).
COPY --chown=dpk:root data-processing-dist/ data-processing-dist/
RUN uv pip install data-processing-dist/${DPK_WHEEL_FILE_NAME}

# END OF STEPS destined for a data-prep-kit base image 

COPY --chown=dpk:root dpk_text_encoder/ dpk_text_encoder/
COPY --chown=dpk:root test-data/ test-data/
COPY --chown=dpk:root requirements.txt requirements.txt
RUN uv pip install ${PIP_INSTALL_EXTRA_ARGS} --no-cache-dir -r requirements.txt

# Set environment
ENV PYTHONPATH=/home/dpk
ENV PATH="/home/dpk/.local/bin:${PATH}" 
ENV HOME=/home/dpk

# Put these at the end since they seem to upset the docker cache.
ARG BUILD_DATE
ARG GIT_COMMIT
ARG TRANSFORM_PATH
ARG GIT_URL
ENV GIT_URL=$GIT_URL
ENV TRANSFORM_PATH=$TRANSFORM_PATH
ENV BUILD_DATE=$BUILD_DATE
ENV GIT_COMMIT=$GIT_COMMIT
LABEL build-date=$BUILD_DATE
LABEL git-commit=$GIT_COMMIT

CMD ["/bin/bash"]
