###
# Usage:
# export $(cat .env | xargs)
# envsubst < ededup-rayjob.yaml | kubectl apply -f -
###
apiVersion: ray.io/v1alpha1
kind: RayJob
metadata:
  name: rayjob-text-encoder # Name of your RayCluster
spec:
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 10
  rayClusterSpec:
    rayVersion: '2.36.1' # Specify the Ray version
    headGroupSpec:
      # Service type for the head node, can be ClusterIP or NodePort
      serviceType: ClusterIP
      # Ray container image for the head node
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
            - name: ray-head
              env:
                - name: DPK_LOG_LEVEL 
                  value: DEBUG
                - name: S3_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-secret
                      key: s3-key
                - name: S3_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-secret
                      key: s3-secret
                - name: S3_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: s3-secret
                      key: s3-endpoint
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-secret
                      key: s3-key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-secret
                      key: s3-secret
                - name: AWS_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: s3-secret
                      key: s3-endpoint      
                - name: HF_HOME
                  value: /tmp/.cache
                - name: WORKER_CPU_REQUEST
                  valueFrom:
                    resourceFieldRef:
                      resource: requests.cpu
              image: quay.io/dataprep1/data-prep-kit/text_encoder-ray:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 6379 # Ray port
                  name: ray-client
                - containerPort: 8265 # Ray Dashboard port
                  name: dashboard
              resources:
                requests:
                  cpu: 8
                  memory: 8Gi
                  ephemeral-storage: 2Gi
                limits:
                  cpu: 8
                  memory: 8Gi
                  ephemeral-storage: 2Gi
    workerGroupSpecs:
      - groupName: worker-group
        replicas: 2 # Initial number of worker nodes
        minReplicas: 2
        maxReplicas: 2
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                env:
                  - name: DPK_LOG_LEVEL 
                    value: DEBUG
                  - name: S3_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: s3-secret
                        key: s3-key
                  - name: S3_SECRET_KEY
                    valueFrom:
                      secretKeyRef:
                        name: s3-secret
                        key: s3-secret
                  - name: S3_ENDPOINT
                    valueFrom:
                      secretKeyRef:
                        name: s3-secret
                        key: s3-endpoint
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: s3-secret
                        key: s3-key
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: s3-secret
                        key: s3-secret
                  - name: AWS_ENDPOINT
                    valueFrom:
                      secretKeyRef:
                        name: s3-secret
                        key: s3-endpoint      
                  - name: HF_HOME
                    value: /tmp/.cache
                image: quay.io/dataprep1/data-prep-kit/text_encoder-ray:latest
                imagePullPolicy: Always
                resources:
                  requests:
                    cpu: 8
                    memory: 32Gi
                    ephemeral-storage: 2Gi
                  limits:
                    cpu: 8
                    memory: 32Gi
                    ephemeral-storage: 2Gi
  # Job details
  # The command to execute the Python script
  entrypoint: >
    python3 -m dpk_text_encoder.ray.runtime
    --run_locally False
    --text_encoder_model_name "$TEXT_ENCODER_MODEL_NAME"
    --text_encoder_content_column_name "$TEXT_ENCODER_CONTENT_COLUMN_NAME"
    --text_encoder_output_embeddings_column_name "embeddings"
    --text_encoder_lanceDB_batch_size 128
    --text_encoder_embedding_batch_size 8
    --text_encoder_lanceDB_table_name "$TEXT_ENCODER_LANCEDB_TABLE_NAME"
    --text_encoder_lanceDB_fragments_json_folder "$TEXT_ENCODER_LANCEDB_FRAGMENTS_JSON_FOLDER"
    --text_encoder_lanceDB_data_uri "$TEXT_ENCODER_LANCEDB_DATA_URI"
    --data_s3_config '{"input_folder": "$TEXT_ENCODER_INPUT_FOLDER", "output_folder": "$TEXT_ENCODER_OUTPUT_FOLDER"}'
    --runtime_worker_options '{"num_cpus": 6, "memory": 20000000000, "max_restarts": 0, "max_task_retries": 0,}'
    --runtime_creation_delay 1
    --runtime_num_workers $RUNTIME_NUM_WORKERS
    --data_checkpointing False

#    --data_max_files -1
#    --data_num_samples -1

