FROM docker.io/python:3.10.14-slim-bullseye

RUN pip install --upgrade --no-cache-dir pip
RUN pip install uv

# install pytest
RUN uv pip install --no-cache-dir  --system pytest

# for OpenCV dependencies
RUN apt-get update && \
    apt-get install ffmpeg libsm6 libxext6  -y && \
    apt-get clean

# Create a user and use it to run the transform
RUN useradd -ms /bin/bash dpk
USER dpk
WORKDIR /home/dpk
RUN uv venv /home/dpk/venv
ENV PATH="/home/dpk/venv/bin:$PATH"
ARG DPK_WHEEL_FILE_NAME
ARG TRANSFORM_NAME

# Copy and install data processing libraries 
# These are expected to be placed in the docker context before this is run (see the make image).
COPY --chown=dpk:users data-processing-dist data-processing-dist
RUN uv pip install data-processing-dist/${DPK_WHEEL_FILE_NAME}

# END OF STEPS destined for a data-prep-kit base image 

COPY --chown=dpk:users dpk_${TRANSFORM_NAME}/ dpk_${TRANSFORM_NAME}/

COPY models models

ARG EXTRA_INDEX_URL
COPY --chown=dpk:users requirements*.txt .
RUN uv pip install --no-cache-dir -r requirements.txt
RUN if [ -f requirements-private.txt ]; then uv pip install --extra-index-url ${EXTRA_INDEX_URL} -r requirements-private.txt; fi

# Set environment
ENV PYTHONPATH /home/dpk

# Put these at the end since they seem to upset the docker cache.
ARG BUILD_DATE
ARG GIT_COMMIT
ARG TRANSFORM_PATH
ARG GIT_URL
ENV GIT_URL=$GIT_URL
ENV TRANSFORM_PATH=$TRANSFORM_PATH
ENV BUILD_DATE=$BUILD_DATE
ENV GIT_COMMIT=$GIT_COMMIT
LABEL build-date=$BUILD_DATE
LABEL git-commit=$GIT_COMMIT