ARG BASE_IMAGE=docker.io/rayproject/ray:2.36.1-py311

FROM ${BASE_IMAGE}

USER root
RUN chown ray:root /home/ray && chmod g=u /home/ray
USER ray
RUN pip install uv
RUN uv venv /home/ray/venv
ENV PATH="/home/ray/venv/bin:$PATH"
RUN mkdir -p /home/ray/.cache/huggingface/hub 

RUN pip install --upgrade --no-cache-dir pip
RUN pip install uv

# install pytest
RUN uv pip install --no-cache-dir  --system pytest
ARG DPK_WHEEL_FILE_NAME
ARG TRANSFORM_NAME

# Copy and install data processing libraries 
# These are expected to be placed in the docker context before this is run (see the make image).
COPY --chmod=775 --chown=ray:root data-processing-dist data-processing-dist
RUN  uv pip install --no-cache-dir data-processing-dist/${DPK_WHEEL_FILE_NAME}[ray]

COPY --chmod=775 --chown=ray:root dpk_${TRANSFORM_NAME}/ dpk_${TRANSFORM_NAME}/

COPY --chown=ray:root requirements.txt requirements.txt 
RUN uv pip install --no-cache-dir -r requirements.txt

RUN python -c 'import nltk; nltk.download("punkt_tab")'

# Set environment
ENV PYTHONPATH /home/ray

# Put these at the end since they seem to upset the docker cache.
ARG BUILD_DATE
ARG GIT_COMMIT
ARG TRANSFORM_PATH
ARG GIT_URL
ENV GIT_URL $GIT_URL
ENV TRANSFORM_PATH $TRANSFORM_PATH
ENV BUILD_DATE $BUILD_DATE
ENV GIT_COMMIT $GIT_COMMIT
LABEL build-date=$BUILD_DATE
LABEL git-commit=$GIT_COMMIT
